trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals allenl-2404

steps:
- script: |
    echo "Check Java version"
    java -version
  displayName: 'Check Java version'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/java-21-openjdk-amd64'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    goals: 'clean install'

- script: |
    wget https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/latest/synopsys-bridge-linux64.zip
    unzip synopsys-bridge-linux64.zip
    chmod +x synopsys-bridge
    ./synopsys-bridge --detect.project.name="Webgoat" \
                      --detect.project.version.name="$(Build.SourceBranchName)"
  displayName: 'Run Black Duck Scan'